### ISSUE TITLE
Not able to install PyTos

### ISSUE THREAD

**Issue by LucaTino** [Tufin/pytos#22]

**Comment by marioland** [comment]
Hi Luca

Due to its direct and indirect dependencies, pytos is not able to be run on windows. 
I cannot recommend to run pytos production installation on a windows OS.

Nevertheless I also do my development on a windows box. I therefor have some hacks I need to do to make pytos run for tests on windows:

- Comment out fcntl in  pytos/common/functions/utils.py 
- Comment out fcntl in   pytos\securechange\xml_objects\rest.py
- Comment out FileMonitor in 2 lines in  pytos/pytos/common/functions/config.py
- Comment out netifaces pytos\common\functions\network.py, line 3 171-174
- Comment out dns pytos\common\functions\network.py
- Comment out lxml and pyinotify in requirement.txt 
- Put in requirement.txt  netaddr, paramiko, mako, requests_toolbelt
- Run test_secure_track_helper_unittest.py

I also already opened a issue #22 for that purpose.

cheers
mario
